import type { Metadata } from "next";
import "./globals.css";
import ClientSceneWrapper from "@/components/ClientSceneWrapper";
import TransitionElement from "@/components/TransitionElement";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative text-blue bg-black overflow-hidden w-full">
        <TransitionElement />
        <ClientSceneWrapper scene="gradients" key="scene" />
        {children}
      </body>
    </html>
  );
}
